[
            'Smooth jazz fusion, laidback saxophone, ambient, sultry piano, dynamic bassline',
            'Edgy punk, distorted guitar, high-energy, booming drums, raw vocals',
            'Funky afrobeat, vibrant brass, groovy, rhythmic percussion, upbeat bass',
            'Ethereal synthwave, dreamy synths, chill, soothing pads, hypnotic arpeggios',
            'Spicy salsa, vibrant horns, upbeat, pulsating rhythms, melodic bass',
            'Gritty blues, raw harmonica, mellow, haunting guitar, rhythmic drums',
            'Trippy dubstep, experimental synth, ambient, heavy-hitting bass, syncopated beats',
            'Mellow R&B, sultry vocals, chill, harmonic backing vocals, smooth bassline',
            'Upbeat pop, catchy hook, energetic, dynamic drums, melodic bass',
            'Groovy disco, funky guitar, upbeat, rhythmic bassline, harmonic strings',
            'Minimalistic techno, ambient pads, chill, pulsating kick drum, evolving synth melody',
            'Dreamy psychedelic rock, vintage guitar, laidback, hypnotic bass, rhythmic drums',
            'Experimental electronica, trippy synths, ambient, progressive structure, dynamic bassline',
            'Jazzy hip hop, smooth saxophone, mellow, chill beat, melodic bass',
            'Euphoric trance, pulsating synth, uplifting, energetic drums, harmonious pads',
            'Retro country, twangy guitar, laidback, soothing harmonica, rhythmic bass',
            'Vintage ska, upbeat horns, energetic, syncopated guitar, bouncing bass',
            'Sultry soul, emotive vocals, chill, rhythmic organ, mellow bassline',
            'Edgy punk, distorted guitar, high-energy, booming drums, raw vocals',
            'Classical piano piece, serene strings, ambient, melodic theme, dramatic orchestration',
            'Ambient classical, serene violin, chill, dreamy piano, ethereal orchestra',
            'Experimental grunge, distorted bass, gritty, raw vocals, booming drums',
            'Retro funk, groovy bassline, vibrant brass, rhythmic guitar, upbeat drums',
            'Mellow bossa nova, soothing guitar, laidback, smooth saxophone, rhythmic drums',
            'Dreamy shoegaze, ethereal guitars, chill, ambient synth, heavy-hitting drums',
            'Upbeat ska-punk, vibrant horns, energetic, distorted guitar, bouncing bass',
            'Vintage bluegrass, twangy banjo, laidback, rhythmic fiddle, dynamic bass',
            'Trippy ambient, experimental synth, chill, hypnotic pads, rhythmic drums',
            'Melodic metal, heavy guitar, energetic, haunting vocals, hard-hitting drums',
            'Sultry neo-soul, emotive vocals, mellow, harmonic keys, smooth bass',
            'Groovy nu-disco, funky bassline, upbeat, dynamic synth, rhythmic drums',
            'Euphoric hardstyle, pulsating synth, high-energy, heavy kick drum, rhythmic snares',
            'Laidback folk, acoustic guitar, soothing vocals, harmonic violin, mellow bass',
            'Experimental IDM, glitchy synths, ambient, progressive beats, dynamic bass',
            'Smooth reggae, chill guitar, laidback, rhythmic drums, melodic bass',
            'Gritty rock n roll, raw guitar, high-energy, booming drums, rhythmic bass',
            'Ethereal trip-hop, dreamy synth, chill, dynamic beat, smooth bass',
            'Funky swing, vibrant horns, upbeat, rhythmic double bass, energetic drums',
            'Ambient drone, ethereal synth, chill, evolving textures, hypnotic rhythm',
            'Energetic drum n bass, pulsating synth, high-energy, fast-paced drums, dynamic bassline'
        ]